name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          persist-credentials: false

      - run: npm install

      - run: npm run build

      - run: npm run check

      - run: npm run test -- run
